### ISSUE TITLE
Your detector seems to be working just fine.

### ISSUE THREAD

**Issue by john0isaac** [manthanpatel98/Covid-19-Detection#2]
Amazing!
![Screenshot 2022-03-22 231745](https://user-images.githubusercontent.com/64026625/159577765-0e2eaec0-6e6a-4a9b-b88a-78ddfd3a6407.png)

**Comment by manthanpatel98** [comment]
Hello John, Purpose of this test project is to learn how to build a CNN model. It does not claim any guarantee regarding the outcome. Also the project is supposed to take X-Ray images as an input. It is not made to take different inputs as it is a test project.
